name: Java CI with Maven

on:
  push:
    branches: [ "TestCI" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: devops
        ports:
          - "3306:3306"
        volumes:
          - mysql_data:/var/lib/mysql

      selenium:
        image: selenium/standalone-chrome
        ports:
          - "4444:4444"

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' 
          cache: maven

      # Build Backend with Maven
      - name: Build Backend with Maven
        working-directory: backend
        run: mvn clean verify

      # Run tests
      - name: Run Backend Tests
        working-directory: backend
        run: mvn test

      # Install Angular
      - name: Install Angular
        run: npm install -g @angular/cli@latest

      # Install Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1


      # Install Frontend dependencies & run tests
      - name: Install dependencies & run tests
        working-directory: frontend
        run: |
          npm install
          ng test --browsers=ChromeHeadless --progress=false --watch=false --code-coverage --source-map=false

      # Docker login
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:         
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"


      # Build Docker images
      - name: Build Docker images
        run: |
          docker build -t acouderc1/front -f frontend/Dockerfile frontend
          docker build -t acouderc1/back -f backend/Dockerfile backend

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Stop all running containers to free up ports
      - name: Stop existing containers
        run: |
          docker ps -q | xargs -r docker stop
          docker network prune -f

      # Launch containers
      - name: Launch containers
        run: docker-compose up -d

      # Install Selenium
      - name: Install Selenium
        run: |
          pip install -U pip
          pip install selenium

      # Run Selenium tests
      - name: Run Selenium tests
        working-directory: tests
        run: python StartTest.py

      # Push images to Docker Hub
      - name: Push Docker images
        run: |
          docker push acouderc1/front
          docker push acouderc1/back
