name: Java CI with Maven

on:
  push:
    branches: [ "TestCI" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: devops
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot" --health-interval=10s --health-timeout=5s --health-retries=3
      
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - "4444:4444"
        options: --shm-size=2g

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' 
          cache: maven

      # Build Backend with Maven
      - name: Build Backend with Maven
        working-directory: backend
        run: mvn clean verify

      # Run tests
      - name: Run Backend Tests
        working-directory: backend
        run: mvn test

      # Install Node.js (version spécifique pour assurer la compatibilité)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Install Angular CLI globalement
      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest

      # Install Frontend dependencies
      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm install

      # Run Frontend unit tests
      - name: Run Frontend unit tests
        working-directory: frontend
        run: |
          ng test --browsers=ChromeHeadless --progress=false --watch=false --code-coverage --source-map=false

      # Vérifier que Selenium est prêt
      - name: Vérifier que Selenium est prêt
        run: |
          echo "Vérification de la disponibilité de Selenium..."
          for i in {1..12}; do
            if curl -s http://localhost:4444/wd/hub/status | grep -q "\"ready\": true"; then
              echo "Selenium est prêt!"
              break
            fi
            echo "Attente de Selenium... ($i/12)"
            sleep 5
          done
          curl -s http://localhost:4444/wd/hub/status || echo "Impossible de connecter à Selenium"

      # Build and serve the frontend (avec plus de temps d'attente)
      - name: Build and serve frontend
        working-directory: frontend
        run: |
          echo "Construction du frontend..."
          ng build --configuration=production
          echo "Démarrage du serveur frontal..."
          nohup ng serve --host 0.0.0.0 --port 4200 --disable-host-check &
          PID=$!
          echo "Processus frontend démarré avec PID: $PID"
          
          # Attendre que le frontend soit disponible
          echo "Attente du démarrage du frontend..."
          MAX_ATTEMPTS=30
          ATTEMPTS=0
          READY=false
          while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
            if curl -s http://localhost:4200 > /dev/null; then
              echo "Frontend est prêt!"
              READY=true
              break
            fi
            ATTEMPTS=$((ATTEMPTS+1))
            echo "Attente du frontend... ($ATTEMPTS/$MAX_ATTEMPTS)"
            sleep 2
          done
          
          if [ "$READY" = false ]; then
            echo "Frontend n'a pas démarré correctement. Vérification des logs:"
            cat nohup.out
            exit 1
          fi

      # Debug des services
      - name: Debug des services
        run: |
          echo "== Vérification des ports ouverts =="
          netstat -tuln | grep -E '4200|4444|8080|3306'
          echo "== Vérification des processus en cours =="
          ps aux | grep -E 'selenium|ng serve'
          echo "== Vérification du service Selenium =="
          curl -v http://localhost:4444/wd/hub/status || echo "Selenium n'est pas accessible"
          echo "== Vérification du frontend =="
          curl -v http://localhost:4200 || echo "Frontend n'est pas accessible"
          echo "== Contenu du répertoire frontend =="
          ls -la frontend/
          echo "== Logs du frontend =="
          cat frontend/nohup.out || echo "Pas de logs trouvés"

      # Install Python and Selenium
      - name: Install Python and Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      # Run Selenium tests avec délai supplémentaire
      - name: Run Selenium tests
        working-directory: tests
        env:
          FRONTEND_URL: "http://localhost:4200"
          SELENIUM_URL: "http://localhost:4444/wd/hub"
        run: |
          echo "Attente supplémentaire pour s'assurer que le frontend est complètement initialisé..."
          sleep 15
          python StartTest.py

      # Docker login
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:         
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      # Build Docker images
      - name: Build Docker images
        run: |
          docker build -t acouderc1/front -f frontend/Dockerfile frontend
          docker build -t acouderc1/back -f backend/Dockerfile backend

      # Push images to Docker Hub
      - name: Push Docker images
        run: |
          docker push acouderc1/front
          docker push acouderc1/back